### List all messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
Content-Type: application/json

{
    "content": "Hello World 1!"
}

### Get a message
GET http://localhost:3000/messages/5071

### TEST
GET http://localhost:3000/asdasds