### Hello World
GET http://localhost:3000/

### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "dyla5n@morison.org",
  "password": "asdlfkasdasdajsd"
}
### Sign in user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "dylan@morison.org",
  "password": "asdlfkasdasdajsd"
}

### Signout
POST http://localhost:3000/auth/signout

### WHOAMI
GET http://localhost:3000/auth/whoami

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user with the given id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email" : "b@aaaaa.com"
}

# ### Set a color
# GET http://localhost:3000/auth/colors/green

# ### Get a color
# GET http://localhost:3000/auth/colors